### ISSUE TITLE
TextInputField not working properly on iOS 10

### ISSUE THREAD

**Issue by huynhphan89** [luximetr/AnyFormatKit#4]
iOS 10, TextInputField formats well on typing, but when done it becomes empty

**Comment by yunustek** [comment]
I have the same issue.
when you close the keyboard, the text is delete!

**Comment by Robuske** [comment]
Also the same issue.
Happens anytime the selection leaves the Text Field, so it happens if you're switching between Text Fields too.
Also, it actually goes back to the state it was before the user started the input. So if I set it to a certain value initially, if the user tries to change it when it leaves the field it goes back to the value I set before.

**Comment by jvanzummeren** [comment]
Fixed in version 0.1.5
